# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: .NET
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '6.x'
        includePrerelease: true
        preferLatestVersion: true
    
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - run: >
        dotnet build
        /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }}
        /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}
        /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
        /p:PackageVersion=${{ steps.gitversion.outputs.semVer }}

  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Run tests
      run: dotnet test --configuration Release