// <auto-generated />
namespace SupportManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_User_IsObserver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_User_IsObserver));
        
        string IMigrationMetadata.Id
        {
            get { return "202609290840207_Add_User_IsObserver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
